# Generated by Django 5.2.8 on 2025-12-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Asistió'), ('F', 'Faltó'), ('J', 'Falta justificada')], default='A', max_length=1)),
                ('justificacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10)),
                ('categoria', models.CharField(choices=[('Respeto', 'Respeto'), ('Responsabilidad', 'Responsabilidad'), ('Disciplina', 'Disciplina'), ('Solidaridad', 'Solidaridad'), ('Academico', 'Académico')], default='Academico', max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inconsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
