# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comportamiento', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante'),
        ),
    ]
