# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comportamiento', '0003_initial'),
        ('estudiantes', '0001_initial'),
        ('matricula', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comportamiento',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comportamientos_registrados', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='comportamiento',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='comportamiento',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='matricula.periodoacademico'),
        ),
        migrations.AddField(
            model_name='inconsistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencias', to='estudiantes.estudiante'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('estudiante', 'fecha'), name='unique_asistencia'),
        ),
        migrations.AddConstraint(
            model_name='inconsistencia',
            constraint=models.UniqueConstraint(fields=('estudiante', 'fecha', 'tipo'), name='unique_inconsistencia'),
        ),
    ]
