# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('tipo', models.CharField(choices=[('historia', 'Reseña Histórica'), ('vision', 'Visión Institucional'), ('mision', 'Misión Institucional'), ('valores', 'Valores Institucionales')], default='historia', max_length=20, verbose_name='Tipo de Información')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('nuevos', 'Nuevos Estudiantes'), ('antiguos', 'Antiguos Estudiantes'), ('P_matricula', 'Proceso de Matrícula'), ('P_admision', 'Proceso de Admisión')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admisión',
                'verbose_name_plural': 'Admisiones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='home_carrusel', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carruseles',
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='noticias', verbose_name='Imagen principal')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace externo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('privacidad', 'Política de Privacidad'), ('cookies', 'Política de Cookies'), ('aviso', 'Aviso Legal')], default='privacidad', max_length=20, verbose_name='Tipo de Página')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Página Legal',
                'verbose_name_plural': 'Páginas Legales',
                'ordering': ['tipo', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Programa')),
                ('nivel', models.CharField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('bachillerato', 'Bachillerato')], max_length=20, verbose_name='Nivel')),
                ('descripcion_corta', models.TextField(max_length=200, verbose_name='Descripción Corta')),
                ('descripcion_completa', models.TextField(verbose_name='Descripción Completa')),
                ('imagen_principal', models.ImageField(upload_to='programas/', verbose_name='Imagen Principal')),
                ('edad_minima', models.IntegerField(blank=True, null=True, verbose_name='Edad Mínima')),
                ('edad_maxima', models.IntegerField(blank=True, null=True, verbose_name='Edad Máxima')),
                ('grados', models.CharField(help_text='Ej: Prejardín a Transición', max_length=100, verbose_name='Grados Ofrecidos')),
                ('horario', models.CharField(default='7:00 AM - 12:00 PM', max_length=100, verbose_name='Horario')),
                ('costo_matricula', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Matrícula')),
                ('costo_pension', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Pensión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado en Home')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
                'ordering': ['orden', 'nivel'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Nombre clave')),
                ('name', models.CharField(max_length=100, verbose_name='Red social')),
                ('link', models.URLField(blank=True, verbose_name='Enlace')),
                ('icon_class', models.CharField(default='bi bi-link', max_length=50, verbose_name='Clase de icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Bienvenida',
                'verbose_name_plural': 'Bienvenidas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='noticias/galeria/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Leyenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web.noticia')),
            ],
            options={
                'verbose_name': 'Imagen de Noticia',
                'verbose_name_plural': 'Imágenes de Noticias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(default='bi-check-circle', max_length=50, verbose_name='Clase de Icono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='web.programaacademico')),
            ],
            options={
                'verbose_name': 'Característica de Programa',
                'verbose_name_plural': 'Características de Programas',
                'ordering': ['orden'],
            },
        ),
    ]
