# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioclase',
            name='asignatura_grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='matricula.asignaturagradoañolectivo'),
        ),
        migrations.AddField(
            model_name='logro',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.asignatura'),
        ),
        migrations.AddField(
            model_name='logro',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='logro',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='matricula.periodoacademico'),
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='academico.nivelescolar'),
        ),
        migrations.AddField(
            model_name='area',
            name='nivel_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='academico.nivelescolar'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioclase',
            unique_together={('asignatura_grado', 'dia_semana', 'hora_inicio')},
        ),
    ]
