# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0002_initial'),
        ('gestioncolegio', '0002_initial'),
        ('matricula', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturagradoañolectivo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_dictadas', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='asignaturagradoañolectivo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_grado', to='gestioncolegio.sede'),
        ),
        migrations.AddField(
            model_name='docentesede',
            name='año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_sede', to='gestioncolegio.añolectivo'),
        ),
        migrations.AddField(
            model_name='docentesede',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_asignadas', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='docentesede',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='gestioncolegio.sede'),
        ),
        migrations.AddField(
            model_name='gradoañolectivo',
            name='año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_año_lectivo', to='gestioncolegio.añolectivo'),
        ),
        migrations.AddField(
            model_name='gradoañolectivo',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados_año_lectivo', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='asignaturagradoañolectivo',
            name='grado_año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_grado', to='matricula.gradoañolectivo'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_academicos', to='gestioncolegio.añolectivo'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academico.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='docentesede',
            unique_together={('docente', 'sede', 'año_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='gradoañolectivo',
            unique_together={('grado', 'año_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='asignaturagradoañolectivo',
            unique_together={('asignatura', 'grado_año_lectivo', 'sede')},
        ),
        migrations.AddConstraint(
            model_name='periodoacademico',
            constraint=models.UniqueConstraint(fields=('año_lectivo', 'periodo'), name='unique_periodo_por_año_lectivo'),
        ),
    ]
