# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('gestioncolegio', '0001_initial'),
        ('matricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='acudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudiente_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='gestioncolegio.añolectivo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado_año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='matricula.gradoañolectivo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='gestioncolegio.sede'),
        ),
        migrations.AddField(
            model_name='nota',
            name='asignatura_grado_año_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.asignaturagradoañolectivo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.periodoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'año_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'asignatura_grado_año_lectivo', 'periodo_academico')},
        ),
    ]
