# Generated by Django 5.2.8 on 2025-12-15 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestioncolegio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriasistema',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='añolectivo',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='años_lectivos', to='gestioncolegio.colegio'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='año_lectivo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestioncolegio.añolectivo'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='colegio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='gestioncolegio.colegio'),
        ),
        migrations.AddField(
            model_name='notificacionsistema',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recursoscolegio',
            name='colegio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestioncolegio.colegio'),
        ),
        migrations.AddField(
            model_name='sede',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_gestion', to='gestioncolegio.colegio'),
        ),
        migrations.AddField(
            model_name='sede',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_gestion_dirigidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='añolectivo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='años_lectivos', to='gestioncolegio.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='añolectivo',
            unique_together={('colegio', 'sede', 'anho')},
        ),
    ]
